# Generated by Django 5.0 on 2023-12-17 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupuni',
            options={'verbose_name': 'Gurux', 'verbose_name_plural': 'Guruxlar'},
        ),
        migrations.RemoveField(
            model_name='groupuni',
            name='group_students',
        ),
        migrations.AddField(
            model_name='groupuni',
            name='group_students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
